apiVersion: v2
name: bedindustries-microservice-postiz
description: A Social Media Scheduling App
type: application
version: 1.0.5
appVersion: "1.3.0"
maintainers:
  - name: bedindustries
    email: manpreet2760@gmail.com
keywords:
  - social media
  - marketing
  - scheduling
  - queue
home: https://postiz.com
sources:
  - https://github.com/gitroomhq/postiz-app
  - https://github.com/gitroomhq/postiz-helmchart
